Kit/ConvertKitSDK-PHP

composer.json
1. Removed version in composer, in the hopes that the project can use
tags
2. Prefer stable for packages it pulls in
3. PHP min version updated to 5.5 as included project Guzzle 6.3 requires php 5.5+
Note that without the use of tags/releases in Github, users receive the following error when installing via `composer require ...`:
> Could not find a version of package convertkit/convertkitapi matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.
=> Updating composer file

src/ConvertKit_API.php
Changed the make_request method in the ConvertKit_API.php file to the public. Since there are lots of API endpoint that are not available as methods in the wrapper, this would allow users to make requests to API endpoints.
=> Changed make_request method to public

README.md
Composer is a popular way to ingest PHP code these days. This project already supports composer but did not yet have installation instructions. Adding those for convenience for future users.
=> Add installation instructions for composer

composer.json
First time doing this...updated requirements to allow for Laravel 6+ installs which default to Monolog 2
=> Change monolog requirement for conflict with Laravel

.gitignore, composer.json
Bumps:
- Minimum PHP version to `7.4`
- `guzzlehttp/guzzle` to between `6.5` and `7.0`, depending on PHP version (resolves https://github.com/ConvertKit/ConvertKitSDK-PHP/pull/27, https://github.com/ConvertKit/ConvertKitSDK-PHP/pull/20, https://github.com/ConvertKit/ConvertKitSDK-PHP/issues/26)
For testing:
- Bumps PHPUnit to between `5.7` and `9.0`, depending on PHP version
- Adds codesniffer and static analysis packages, for use in a later testing PR
=> Bump dependencies

.github/workflows/tests.yml, phpcs.xml, src/ConvertKit_API.php
Applies PSR-12 coding standards to the API class, with some exclusions to prevent conflicts with Squiz coding standards.
Runs coding standard checks for PRs on the GitHub Action
=> Apply Coding Standards

src/ConvertKit_API.php
Moves specifying the `api_version` property into `make_request()`, instead of repeating it in every API function.
=> Move `api_version` property into `make_request()`

src/ConvertKit_API.php
Replaces the `check_if_subscriber_in_array()` function, as we query the API by `email_address` - so inspecting the response’s `total_subscribers` is sufficient.
=> Replace `check_if_subscriber_in_array()` function

TESTING.md, src/ConvertKit_API.php, tests/ConvertKitAPITest.php
Fixes test failures when asserting the sort order of two items when both items have the same date and time.
Adds section to testing guide covering using CodeSniffer for main code.
=> Fix sort order tests

src/ConvertKit_API.php
Adds a `User-Agent` header to every API request, allowing us to identify which API requests originate from this PHP SDK.
=> Include User Agent header in API requests

phpcs.xml, src/ConvertKit_API.php
- Moves `create_log()` calls from each API function to HTTP verb function (get, post, delete, put)
- Removes unnecessary initialization of variables for some API function calls
- Refactors `get_resources()` to improve code readability
=> Refactor logging and API calls

TESTING.md, phpstan.neon.dist, phpstan.neon.example, src/ConvertKit_API.php
Adds PHPStan for static analysis, covering:
- Correct variable declarations
- More accurate typehints in docblocks when specifying or returning arrays
- Moving `InvalidArgumentException` checks onto individual `if` blocks to prevent false positive reports in PHPStan
- Passing valid variable types to functions such as `preg_replace`
- Improved type checking on return values such as `json_encode`
=> Added PHPStan for Static Analysis

src/ConvertKit_API.php, tests/ConvertKitAPITest.php
Adds the `get_form_subscriptions()` API functions, to call https://developers.convertkit.com/#list-subscriptions-to-a-form.
- `testGetFormSubscriptions`: Tests that fetching subscribers for a valid ConvertKit Form ID works.
- `testGetFormSubscriptionsWithDescSortOrder`: Tests that fetching subscribers for a valid ConvertKit Form ID works with a valid sort order.
- `testGetFormSubscriptionsWithCancelledSubscriberState`: Tests that fetching cancelled subscribers for a valid ConvertKit Form ID works.
- `testGetFormSubscriptionsWithPage`: Tests that fetching subscribers for a valid ConvertKit Form ID works with pagination.
- `testGetFormSubscriptionsWithInvalidFormID`: Tests that a `ClientException` is thrown when an invalid ConvertKit Form ID is specified
=> Add `get_form_subscriptions()` API functions

src/ConvertKit_API.php, tests/ConvertKitAPITest.php
Adds `get_forms()` and `get_landing_pages()` API functions, as a convenience vs. having to call `get_resources('forms')` or `get_resources('landing_pages')`.
Removes unnecessary timeout and encoding headers on requests for resources.
When fetching landing pages, exclude forms from the resultset.
- `testGetForms`: Tests that fetching forms works with expected response data.
- `testGetLandingPages`: Tests that fetching landing pages works with expected response data.
=> Add `get_forms()` and `get_landing_pages()` API functions

src/ConvertKit_API.php, tests/ConvertKitAPITest.php
Updates the `add_subscriber_to_sequence()` API function, to include support for first name, custom fields and tags, per https://developers.convertkit.com/#add-subscriber-to-a-sequence.
Adds tests to improve test coverage of new function arguments.
- `testAddSubscriberToSequenceWithFirstName`: Test that adding a subscriber to a sequence with a first name specified works.
- `testAddSubscriberToSequenceWithCustomFields`: Test that adding a subscriber to a sequence with a custom field works.
- `testAddSubscriberToSequenceWithTagID`: Test that adding a subscriber to a sequence with a tag ID works.
- `testGetSequenceSubscriptionsWithDescSortOrder`: Test that fetching a subscriber's sequences in descending order works.
- `testGetSequenceSubscriptionsWithInvalidSortOrder`: Test that a …
=> Update `add_subscriber_to_sequence()` to support name, custom fields and tags

src/ConvertKit_API.php, tests/ConvertKitAPITest.php
Adds the following API functions to provide API coverage for [Subscribers](https://developers.convertkit.com/#subscribers)
- `update_subscriber()`
- `unsubscribe()`
Outputs a PHP deprecated notice if using `form_unsubscribe()`, because:
- The function name is misleading; it doesn't just unsubscribe the email address from a form,
- The argument supports an array of options; `unsubscribe()` provides the specific supported argument (email address)
`form_unsubscribe()` is not removed at this time, to ensure we don't introduce breaking changes to the SDK. The deprecation notice serves as an early warning to developers to migrate to `unsubscribe()` as we will remove `form_unsubscribe()` at a later date.
- Tests for above functions included.
=> Add Subscriber API functions

src/ConvertKit_API.php, tests/ConvertKitAPITest.php
Adds the following API functions to provide API coverage for [Custom Fields](https://developers.convertkit.com/#custom-fields)
- `get_custom_fields()`
- `add_custom_field()`
- `add_custom_fields()`
- `update_custom_field()`
- `delete_custom_field()`
- Tests for above functions included.
=> Add Custom Field API functions

src/ConvertKit_API.php, tests/ConvertKitAPITest.php
Adds a `get_purchase()` function for the [purchases API endpoint](https://developers.convertkit.com/#retrieve-a-specific-purchase).
- `testGetPurchase`: Test that fetching a specific purchase works
- `testGetPurchaseWithInvalidID`: Test that a `ClientException` is thrown when an invalid purchase ID is specified
- `testCreatePurchaseWithMissingData`: Test that a `ClientException` is thrown when creating a purchase with invalid purchase data
=> Add `get_purchase()` function

src/ConvertKit_API.php
Removes code in the API class that stores the results of `get_resources()` and `get_resource()` functions into class properties.
This data isn't cached and doesn't persist beyond a single PHP request life cycle, so it's pointless.
If developers wish to cache the results of an API call (such as a list of forms or landing page HTML markup), they can do so within their application.
=> Removes `$resources` and `$markup` class properties

composer.json, tests/ConvertKitAPITest.php
Permit using `monolog/monolog` `3.x` to ensure this package works with other packages that require `3.x`, such as Laravel 10, as reported [here](https://github.com/ConvertKit/ConvertKitSDK-PHP/pull/63).
PHP < 8.1 will continue to use monolog `2.x`, with our tests running in PHP 7.4 and 8.0 confirming this works.
- `testDebugEnabled`: Test that the debug log is created and written to with expected data when debugging is enabled
- `testDebugDisabled`: Test that the debug log is not created when debugging is disabled
=> Use monolog/monolog 3.x for PHP 8.1+

src/ConvertKit_API.php, tests/ConvertKitAPITest.php
Adds a `debugLogFileLocation` parameter to the class constructor, allowing developers to specify where the log file should be written to, instead of the default `src/logs/debug.log`, which may be public facing.
Masks the API Key and Secret in the log file if detected in the `create_log()` message. 
- `testDebugEnabledWithCustomLogFile`: Test that debug logging works when enabled, a custom debug log file and path is specified and an API call is made.
- `testDebugAPIKeyAndSecretAreMasked`: Test that debug logging works when enabled and an API call is made, with the API Key and Secret masked in the log file.
=> Define log location; mask API credentials

.github/workflows/tests.yml, composer.json, tests/ConvertKitAPITest.php
Adds named arguments to tests for readability, which should help with reviewing future PRs that introduce the v4 API and changed parameter options.
Bumps minimum supported PHP version to 8.0 to support named arguments (8.1 and higher are officially supported by PHP, so likely we'll bump to 8.1 with the v4 API support: https://www.php.net/supported-versions.php). Users of 7.4 and lower can continue to use [`1.3` of our SDK](https://github.com/ConvertKit/ConvertKitSDK-PHP/releases/tag/1.3).
=> Add Named Args to Tests; Bump to PHP 8.0+

.github/workflows/tests.yml, tests/ConvertKitAPITest.php
Tidies up test code by adding `use statements` for `ClientException`, `Dotenv` and the `ConvertKit_API` classes.
=> Move Namespaces to `use` Statements

.github/workflows/tests.yml, src/ConvertKit_API.php, tests/ConvertKitAPITest.php
Adds support for endpoints in the accounts section of the v4 API.
- `testGetAccountColors`: Test that `get_account_colors()` returns the expected data.
- `testUpdateAccountColors`: Test that `update_account_colors()` updates the account's colors.
- `testGetCreatorProfile`: Test that `get_creator_profile()` returns the expected data.
- `testGetEmailStats`: Test that `get_email_stats()` returns the expected data.
- `testGetGrowthStats`: Test that `get_growth_stats()` returns the expected data.
- `testGetGrowthStatsWithStartDate`: Test that `get_growth_stats()` returns the expected data when a start date is specified.
- `testGetGrowthStatsWithEndDate`: Test that `get_growth_stats()` returns the expected data when an end date is specified.
=> v4 API: Accounts

src/ConvertKit_API.php, tests/ConvertKitAPITest.php
Adds support for endpoints in the forms section of the v4 API.
- `testGetFormSubscriptionsWithBouncedSubscriberState`: Test that get_form_subscriptions() returns the expected data when a valid Form ID is specified and the subscription status is cancelled.
- `testGetFormSubscriptionsWithAddedAfterParam`: Test that get_form_subscriptions() returns the expected data when a valid Form ID is specified and the added_after parameter is used.
- `testGetFormSubscriptionsWithAddedBeforeParam`: Test that get_form_subscriptions() returns the expected data when a valid Form ID is specified and the added_before parameter is used.
- `testGetFormSubscriptionsWithCreatedAfterParam`: Test that get_form_subscriptions() returns the expected data when a valid Form ID is specified and the created_after …
=> v4 API: Forms

src/ConvertKit_API.php, tests/ConvertKitAPITest.php
Adds support for endpoints in the sequences section of the v4 API.
- `testGetSequencesPagination`: Test that get_sequences() returns the expected data when pagination parameters and per_page limits are specified.
- `testGetSequenceSubscriptionsWithBouncedSubscriberState`: Test that get_sequence_subscriptions() returns the expected data when a valid Sequence ID is specified and the subscription status is cancelled.
- `testGetSequenceSubscriptionsWithAddedAfterParam`: Test that get_sequence_subscriptions() returns the expected data when a valid Sequence ID is specified and the added_after parameter is used.
- `testGetSequenceSubscriptionsWithAddedBeforeParam`: Test that get_sequence_subscriptions() returns the expected data when a valid Sequence ID is specified and the added_before …
=> v4 API: Sequences

README.md, src/ConvertKit_API.php, tests/ConvertKitAPITest.php
Exposes the `GuzzleHttp\Psr7\Response` object via using `getResponseInterface()`, allowing the consumer to check e.g. a 2xx HTTP status code, header or other properties:
```php
$result = $api->add_subscriber_to_form(12345, 'joe.bloggs@convertkit.com');
$code = $api->getResponseInterface()->getStatusCode(); // 200 OK if e.g. a subscriber already added to the specified form, 201 Created if the subscriber added to the specified form for the first time.
```
- `testGetResponseInterface`: Test that a valid PSR-7 response object is returned by `getResponseInterface` and can be interacted with.
- `testClientInterfaceInjection`: Test that a valid PSR-7 response object is returned by `getResponseInterface` when `set_http_client` is used ([PR](https://github.com/ConvertKit/ConvertKitSDK-PHP/pull/68)) …
=> v4 API: Expose `Response` interface

src/ConvertKit_API.php, tests/ConvertKitAPITest.php
Adds support for endpoints in the subscribers section of the v4 API.
Tests pass.
=> v4 API: Subscribers

tests/ConvertKitAPITest.php
Mocks responses for `testCreateTag` and `testCreateTags`, with response objects matching those from the v4 API.
This prevents the ConvertKit account having hundreds of tags created across multiple tests and PRs, due to there being no API method to delete tags.
=> v4 API: Mock Create Tag Tests

src/ConvertKit_API.php, tests/ConvertKitAPITest.php
- Adds `sku` to the `products` array for testing, as this is supported in the API ([docs](https://developers.convertkit.com/v4.html#create-a-purchase), [slack](https://n7studios-workspace.slack.com/archives/C02KFR6N1GF/p1711661766953569?thread_ts=1711640295.025739&cid=C02KFR6N1GF))
- Reorders `create_purchase` method parameters to ensure required parameters listed first
- Removes blank and null parameters prior to calling the create purchase endpoint
- `testCreatePurchaseWithInvalidEmailAddress`: Test that a `ClientException` is thrown when an invalid email address is specified
- `testCreatePurchaseWithBlankTransactionID`: Test that a `ClientException` is thrown when no transaction ID defined
- `testCreatePurchaseWithNoProducts`: Test that a `ClientException` is thrown when no `products` …
=> v4 API: Purchases: SKU and Required / Optional Fields

src/ConvertKit_API.php, tests/ConvertKitAPITest.php
Adds support for endpoints in the webhooks section of the v4 API.
Tests pass.
=> v4 API: Webhooks

tests/ConvertKitAPITest.php
Create a subscriber before subscribing them to a resource, such as a form, tag or sequence (vs. using an existing subscriber that is already subscribed to a resource), to improve the accuracy of tests.
=> v4 API: Improve Subscriber Tests

src/ConvertKit_API.php, tests/ConvertKitAPITest.php
Runs tests for fetching HTML resources (legacy forms, landing pages, legacy landing pages), ensuring the API sets the correct headers.
=> v4 API: Get HTML Resources

.github/workflows/tests.yml, src/ConvertKit_API_Traits.php
Runs tests against PHP 8.4, adding compatibility to fix the `Implicitly marking parameter $value as nullable is deprecated, the explicit nullable type must be used instead` deprecated notice, by using the [Union Type on `null` parameters](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated).
=> Add PHP 8.4 Compatibility

.github/workflows/tests.yml, src/ConvertKit_API_Traits.php, tests/ConvertKitAPITest.php
Updates existing tests:
- Tags: creating a tag that exists returns the tag (previously, the API would return an error)
- Before / after params: set sensible before/after dates, now the test Kit account has had the majority of its test subscribers removed
- Apply the timezone offset (-04:00 or -05:00) depending on whether daylight savings time is active
=> Tests: Update Tests to match API behaviour

src/ConvertKit_API_Traits.php, tests/ConvertKitAPITest.php
Adds a method for [updating a tag name](https://developers.kit.com/api-reference/tags/update-tag-name).
- `testUpdateTagName`: Test that `update_tag_name()` returns the expected data.
- `testUpdateTagNameWithInvalidTagID`: Test that `update_tag_name()` throws a ClientException when an invalid tag ID is specified.
- `testUpdateTagNameWithBlankName`: Test that `update_tag_name()` throws a ClientException when a blank tag name is specified.
=> Add `update_tag_name` method

composer.json, docs/Home.md, docs/classes/ConvertKit_API/ConvertKit_API_Traits.md
Fixes the `composer create-docs` command, which generates the markdown files for the API documentation currently provided, which wasn't working due to a missing composer package.
In the future, it'd be preferable to document the PHP SDK in the Mintlify API docs, as that would be a better source:
https://developers.kit.com/api-reference/accounts/get-current-account - not sure if there's a repo for that.
=> Fix API Docs

TESTING.md, composer.json
=> Add Composer Commands

.github/ISSUE_TEMPLATE/config.yml, DEPLOYMENT.md, SETUP.md, composer.json, src/ConvertKit_API_Traits.php, tests/ConvertKitAPIKeyTest.php, tests/ConvertKitAPIOAuthTest.php, tests/ConvertKitAPITest.php
Changes `convertkit.com` to `kit.com` in the PHP SDK.
Updates wording from ConvertKit to Kit.
=> Update Kit Domain

src/ConvertKit_API_Traits.php, tests/ConvertKitAPITest.php
Adds a method for [fetching a subscriber's stats](https://developers.kit.com/api-reference/subscribers/list-stats-for-a-subscriber).
- `testGetSubscriberStats`: Test that get_subscriber_stats() returns the expected data when using a valid subscriber ID.
- `testGetSubscriberStatsWithInvalidSubscriberID`: Test that get_subscriber_stats() throws a ClientException when an invalid subscriber ID is specified.
=> Add `get_subscriber_stats` method

src/ConvertKit_API_Traits.php, tests/ConvertKitAPITest.php
Adds a method for [fetching a list of broadcast's stats](https://developers.kit.com/api-reference/broadcasts/get-stats-for-a-list-of-broadcasts).
- `testGetBroadcastsStats `: Test that `get_broadcasts_stats()` returns the expected data and pagination works.
- `testGetBroadcastsStatsWithTotalCount`: Test that `get_broadcasts_stats()` includes the total count when required.
=> Add `get_broadcasts_stats` method

.github/ISSUE_TEMPLATE/config.yml, DEPLOYMENT.md, SETUP.md, TESTING.md, composer.json, docs/Home.md, docs/classes/ConvertKit_API/ConvertKit_API_Traits.md, src/ConvertKit_API_Traits.php, tests/ConvertKitAPIKeyTest.php, tests/ConvertKitAPIOAuthTest.php, tests/ConvertKitAPITest.php
Fixes failing tests due to subscriber data stored in the Kit account.
=> Fix Failing Tests
